### ISSUE TITLE
Problems installing the macros

### ISSUE THREAD

**Issue by RufusJWB** [macros4outlook/quotefixmacro#8]
I'm having problems installing the macros in Outlook. In the documentation, you say:
![image](https://user-images.githubusercontent.com/1633499/127321009-ec94982b-192d-4af4-89d6-e2e9d48ff7c7.png)
But there are many files in that directory. Which do I have to install?

**Comment by koppor** [comment]
Thank you for reporting the issue. Maybe, I thought that the name `quotefixmacro` of this repository would indicate that `QuoteFixMacro.bas` would be the file to go. - Alternatively, I thought that importing all files would also be OK.

I updated the documentation to be more clear:

![grafik](https://user-images.githubusercontent.com/1366654/127938965-c6d457e7-ec4b-4edd-9539-755c32e72c53.png)

Please let me know if it works on your side!

**Comment by RufusJWB** [comment]
looks better - thank you! Now I need to get myself a Code Signing Certificate because at our company we can only run signed macros. You do not have a signed version of this macro available?

![image](https://user-images.githubusercontent.com/1633499/127980812-98da5b8c-6a37-44ac-a0b2-cf4345c2ac62.png)

**Comment by koppor** [comment]
Can you "cheat" with a self-signed certificate as outlined at https://support.microsoft.com/en-us/office/digitally-sign-your-macro-project-956e9cc8-bbf6-4365-8bfa-98505ecd1c01? 

1. "Create a self-signing certificate"
2. "Digitally sign a macro project in Excel, PowerPoint, Publisher, Visio, Outlook, or Word"

I hope you can open the VBA editor or is that not possible?
